### ISSUE TITLE
Resources directory written to '?/.config' when inside Docker container

### ISSUE THREAD

**Issue by coemgenuslcp** [pml-lang/pml-companion#86]
When I run PMLC 3.0.0 inside a Docker container on Linux, the resources directory gets written to `?/.config`.  It may be something in how [the resources directory string](https://github.com/pml-lang/pml-companion/blob/15b18a7295d293bb6435a9fdf38ef6802843533c/pmlc-commands/src/main/java/dev/pmlc/commands/Start.java#L18-L19) determines home or wherever, when it is inside the container context.

```dockerfile
# Dockerfile
FROM alpine:latest
RUN wget "https://github.com/pml-lang/pml-companion/releases/download/v3.0.0/pmlc" && chmod +x pmlc
RUN pmlc -version
# or
ENTRYPOINT ["/pmlc", "-version"]
```
```shell
docker build --tag "pmlc" - < Dockerfile
docker run "pmlc" -version
```
```
INFO: Creating shared data directory ?/.config/PML_Companion/3_0
PMLC 3.0.0 2022-08-19
```

The `?` folder appears to be created relative to the current directory.  As a side effect, if you mount the current directory to the container and `WORKDIR` into it inside the Dockerfile, the `?` folder with the `.config/PML` resources subdirectory will be generated inside the current directory, with `root:root` as the owner.

**Comment by pml-lang** [comment]
The root directory for config data is determined by function [userConfigDirectory](https://github.com/pdml-lang/pp-libs/blob/c5ee48ad3a19ec5df5816993366571b1326f0160/pp-basics/src/main/java/dev/pp/basics/utilities/directory/DirectoryConfig.java#L123) in [DirectoryConfig.java](https://github.com/pdml-lang/pp-libs/blob/main/pp-basics/src/main/java/dev/pp/basics/utilities/directory/DirectoryConfig.java).

Here are the relevant Java statements:
```
} else if ( OSName.isUnixOS() ) {
    path = System.getenv ( "XDG_CONFIG_HOME" );
    if ( path == null ) {
        path = OSDirectories.USER_HOME_DIRECTORY + "/.config";
    }
```
As can be seen: The config root directory is retrieved from the OS environment variable [XDG_CONFIG_HOME](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html). If this variable is not defined then `OSDirectories.USER_HOME_DIRECTORY + "/.config"` is used. `OSDirectories.USER_HOME_DIRECTORY` is [defined](https://github.com/pdml-lang/pp-libs/blob/c5ee48ad3a19ec5df5816993366571b1326f0160/pp-basics/src/main/java/dev/pp/basics/utilities/os/OSDirectories.java#L11) as follows:
```
USER_HOME_DIRECTORY = Path.of ( System.getProperty ( "user.home" ) );
```
It seems that inside your container context:

- `XDG_CONFIG_HOME` is not defined
- `System.getProperty ( "user.home" )` returns `?`

... which is the reason why the path evaluates to `?/.config`.

Hence I suggest to explicitly specify the config root directory by defining OS environment variable `XDG_CONFIG_HOME` in your Docker config file.

Please let me know if this solves your problem.

PS: To avoid this situation in the future, all functions in [DirectoryConfig.java](https://github.com/pdml-lang/pp-libs/blob/main/pp-basics/src/main/java/dev/pp/basics/utilities/directory/DirectoryConfig.java) using `OSDirectories.USER_HOME_DIRECTORY` (i.e. `System.getProperty ( "user.home" )`) should check this value. If it is `?`, then there should be a helpful message displayed in the terminal, so that the user knows how to solve the problem.

**Comment by pml-lang** [comment]
> all functions OSDirectories.USER_HOME_DIRECTORY (i.e. System.getProperty ( "user.home" )) should check this value. If it is ?, then there should be a helpful message

[Fixed](https://github.com/pdml-lang/pp-libs/blob/b5ab715a219cbf9e174ddcfc3f2e800947a15302/pp-basics/src/main/java/dev/pp/basics/utilities/os/OSDirectories.java#L22) in version 4.0.0.
